<h2><i class="fa fa-copy"></i> My Orders</h2>
<hr />
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>S No.</th>
            <th>Order No.</th>
            <th>Order Date</th>
            <th>Status</th>
            <th>Order Amount</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php
        $records = $data['records'];
        if(count($records) == 0):
    ?>
        <tr>
            <td colspan="6">
                <h4 class="text-center">
                    No order has been placed yet!
                </h4>
            </td>
        </tr>
    <?php else: ?>
        <?php $counter = 1; foreach ($records as $record): ?>
            <tr>
                <td><?php echo $counter++ ?>.</td>
                <td class="text-center">#<?php echo str_pad($record->getId(), 7, '0', STR_PAD_LEFT) ?></td>
                <td><?php echo $record->getOrderDate() ?></td>
                <td class="text-center">
                    <?php echo $record->getOrderStatus() ?>
                </td>
                <td class="text-center">
                    <i class="fa fa-rupee"></i>
                    <?php echo number_format($record->getGrandTotal(), 2) ?>
                </td>
                <td class="text-right">
                    <div class="btn-group btn-group-sm">
                        <a class="btn btn-primary" href="/customer/view-order/?id=<?php echo $record->getId() ?>"><i class="fa fa-info-circle"></i></a>
                        <?php if(in_array($record->getOrderStatus(), ['Order Placed', 'Processing'])): ?>
                            <button type="button" onclick="doCancelOrder(<?php echo $record->getId() ?>)" class="btn btn-danger">
                                <i class="fa fa-times"></i>
                            </button>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>

<?php \OS\helpers\ViewRenderer::registerHook("FooterCode", function(){ ?>
<script>
    function doCancelOrder(orderId){

    }
</script>
<?php }); ?>