<?php
    /** @var array $data */
    /** @var \OS\models\AdminUser $user */
    $user = $data['user'];
?>
<div id="editProfileWrapper">
    <form method="post" onsubmit="doSaveProfile(this); return false;">
        <div class="modal fade" id="modalEditProfile" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            <i class="fa fa-user-edit"></i> Edit User Profile
                        </h5>
                    </div>
                    <div class="modal-body">
                        <div class="form-group row">
                            <label class="col-form-label col-sm-4" for="userName">Name:</label>
                            <div class="col-sm-8">
                                <input type="text" name="userName" id="userName" class="form-control" value="<?php echo $user->getName(); ?>" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-sm-4" for="emailAddress">Email Address:</label>
                            <div class="col-sm-8">
                                <input type="text" name="emailAddress" id="emailAddress" class="form-control" value="<?php echo $user->getEmailAddress(); ?>" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="btnSaveProfile" type="submit" class="btn btn-primary">
                            <i class="fa fa-check"></i> Save Profile
                        </button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                            <i class="fa fa-times"></i> Cancel
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <script>
        $('#modalEditProfile').on('hidden.bs.modal', function(){
            $('#editProfileWrapper').remove();
        });
        function doSaveProfile(form){
            $.ajax({
                url: '/admin/save-profile',
                type: 'post',
                dataType: 'json',
                data: $(form).serialize(),
                beforeSend: function(){
                    $('#btnSaveProfile').html('<i class="fa fa-cog fa-spin"></i> Please wait...');
                },
                complete: function(){
                    $('#btnSaveProfile').html('<i class="fa fa-check"></i> Save Profile');
                },
                success: function(response){
                    if(response.error){
                        swal({
                            title: 'Error Encountered!',
                            text: response.errorMessage,
                            type: 'error'
                        });
                    }else if(response.success){
                        $('#modalEditProfile').modal('hide');
                        swal({
                            title: 'Profile Saved Successfully!',
                            type: 'success',
                            text: ''
                        }, function(){
                            location["href"] = location.href;
                        });
                    }
                }
            });
        }
    </script>
</div>