<?php
    /** @var array $data */
?>
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.6.0/flatly/bootstrap.min.css" integrity="sha512-5bGVgbI2xuyCes5Q7colxgLChuX/2lidwyC6zFo0Fu7Nb46xf55YcMwojQel2JBxaJoa3w0d14dKek6TbGROfQ==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css" integrity="sha512-hwwdtOTYkQwW2sedIsbuP1h0mWeJe/hFOfsvNKpRB3CkRxq8EW7QMheec1Sgd8prYxGm1OM9OZcGW7/GUud5Fw==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css" integrity="sha512-42kB9yDlYiCEfx2xVwq0q7hT4uf26FUgSIZBK8uiaEnTdShXjwr8Ip1V4xGJMg3mHkUt9nNuTDxunHF0/EgxLQ==" crossorigin="anonymous" />

    <title><?php echo $data['pageTitle']; ?></title>
</head>
<body>

    <br />
    <br />
    <div class="container">
        <h2 class="text-center">
            e-Commerce Admin Panel
        </h2>
        <br />
        <form method="post" onsubmit="doLogin(this); return false;">
            <input type="hidden" name="recordAction" value="login">
            <div class="card m-auto" style="max-width: 450px;">
                <div class="card-header">
                    <h3 class="mb-0">
                        <i class="fa fa-user"></i> Login To Your Account
                    </h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="emailAddress">Email Address</label>
                        <input type="email" name="emailAddress" id="emailAddress" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" required class="form-control">
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-6">
                            <button id="btnSubmit" type="submit" class="btn btn-primary">
                                <i class="fa fa-check"></i> Sign In
                            </button>
                        </div>
                        <div class="col-sm-6 text-right">
                            <button type="button" class="btn btn-secondary" onclick="forgotPassword">
                                Forgot Password?
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <br />
    <br />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js" integrity="sha512-wV7Yj1alIZDqZFCUQJy85VN+qvEIly93fIQAN7iqDFCPEucLCeNFz4r35FCo9s6WrpdDQPi80xbljXB8Bjtvcg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.js" integrity="sha512-MqEDqB7me8klOYxXXQlB4LaNf9V9S0+sG1i8LtPOYmHqICuEZ9ZLbyV3qIfADg2UJcLyCm4fawNiFvnYbcBJ1w==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.js" integrity="sha512-bUg5gaqBVaXIJNuebamJ6uex//mjxPk8kljQTdM1SwkNrQD7pjS+PerntUSD+QRWPNJ0tq54/x4zRV8bLrLhZg==" crossorigin="anonymous"></script>

    <script>
        function doLogin(form){
            $.ajax({
                url: '/admin/login',
                type: 'POST',
                dataType: 'json', //response content type
                data: $(form).serialize(),
                beforeSend: function(){
                    $('#btnSubmit').html('<i class="fa fa-cog fa-spin"></i> Please wait...');
                },
                complete: function(){
                    $('#btnSubmit').html('<i class="fa fa-check"></i> Sign In');
                },
                success: function(res){
                    if(res.error){
                        swal({
                            title: 'Error Encountered!',
                            text: res.errorMessage,
                            type: 'error'
                        });
                    }else if(res.success){
                        swal({
                            title: 'Successfully Signed In!',
                            text: '',
                            type: 'success'
                        }, function(){
                            location.href = "/admin/dashboard";
                        });
                    }
                }
            });
        }
        function forgotPassword(){
        }
    </script>

</body>
</html>