<div class="row">
    <div class="col-sm-8">
        <h1><i class="fa fa-cubes"></i> Manage Product Categories</h1>
    </div>
    <div class="text-sm-right col-sm-4">
        <a href="#modalAddCategory" data-toggle="modal" class="btn btn-primary btn-lg">
            <i class="fa fa-plus"></i> Add Category
        </a>
    </div>
</div>
<hr />
<?php if($data['error']): ?>
<div class="alert alert-danger">
    <i class="fa fa-exclamation-triangle"></i> Failed to load product category list. 
    Please re-try again.
</div>
<?php endif; ?>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th style="width: 75px;">S No.</th>
            <th>Category Name</th>
            <th class="text-center">Status</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if(count($data['records']) == 0): ?>
        <tr>
            <td colspan="4" class="text-center">
                No product category has been added yet!
            </td>
        </tr>
        <?php else: ?>
            <?php $counter = $data['recordCounter']; foreach ($data['records'] as $record): ?>
        <tr>
            <td><?php echo $counter++; ?>.</td>
            <td><?php echo $record->getName() ?></td>
            <td class="text-center">
                <?php if($record->getIsActive()){ ?>
                    <span class="badge badge-success">Active</span>
                <?php }else{ ?>
                    <span class="badge badge-danger">Not Active</span>
                <?php } ?>
            </td>
            <td class="text-right">
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-primary" onclick="doRecordAction(<?php echo $record->getId() ?>, 'edit')">
                        <i class="fa fa-edit"></i>
                    </button>
                    <button type="button" class="btn btn-danger" onclick="doRecordAction(<?php echo $record->getId() ?>, 'delete')">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            </td>
        </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>
<?php if($data['totalPages'] > 1): ?>
<nav>
    <ul class="pagination pagination-sm">
        <?php for($pageCounter = 1; $pageCounter <= $data['totalPages']; $pageCounter++): ?>
            <?php if($pageCounter == $data['currentPage']): ?>
        <li class="page-item active">
            <a href="#" class="page-link"><?php echo $pageCounter ?></a>
        </li>
            <?php else: ?>
        <li class="page-item">
            <a href="/admin/product-category/list<?php echo ($pageCounter == 1 ? '' : '?page='.$pageCounter) ?>" class="page-link"><?php echo $pageCounter ?></a>
        </li>
            <?php endif; ?>
        <?php endfor; ?>
    </ul>
</nav>
<?php endif; ?>


<!-- Modal: Add Category -->
<form method="post" onsubmit="doAddCategory(this); return false;">
    <div class="modal fade" id="modalAddCategory" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">
                        <i class="fa fa-plus"></i> Add Category
                    </h5>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-form-label col-sm-4" for="categoryName">Category Name:</label>
                        <div class="col-sm-8">
                            <input type="text" name="categoryName" id="categoryName" class="form-control" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-form-label col-sm-4" for="categoryDescription">Description:</label>
                        <div class="col-sm-8">
                            <textarea id="categoryDescription" name="categoryDescription" placeholder="( Optional )" class="form-control" rows="3"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-form-label col-sm-4">Is Active?</label>
                        <div class="col-sm-8">
                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" id="isActiveYes" name="isActive" value="yes" class="custom-control-input">
                                <label class="custom-control-label" for="isActiveYes">Activate It</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" id="isActiveNo" name="isActive" value="no" checked class="custom-control-input">
                                <label class="custom-control-label" for="isActiveNo">Disable It</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="btnAddCategory" class="btn btn-primary">
                        <i class="fa fa-check"></i> Add
                    </button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        <i class="fa fa-times"></i> Cancel
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>


<?php OS\helpers\ViewRenderer::registerHook("FooterCode", function(){ ?>
<script>
    function doAddCategory(form){
        $.ajax({
            url: '/admin/product-category/add',
            type: 'post',
            dataType: 'json',
            data: $(form).serialize(),
            beforeSend: function(){
                $('#btnAddCategory').html('<i class="fa fa-cog fa-spin"></i> Please wait...');
            },
            complete: function(){
                $('#btnAddCategory').html('<i class="fa fa-check"></i> Add');
            },
            success: function(response){
                if(response.error){
                    swal({
                        title: 'Error Encountered!',
                        text: response.errorMessage,
                        type: 'error'
                    });
                }else if(response.success){
                    swal({
                        title: 'Product Category Added Successfully!',
                        text: '',
                        type: 'success'
                    }, function(){
                        location['href'] = location.href;
                    });
                }
            }
        });
    }
    function doRecordAction(recordId, action){
        switch(action){
            case 'edit': {
                NProgress.start();
                $.ajax({
                    url: '/admin/product-category/edit/' + recordId,
                    type: 'get',
                    dataType: 'html',
                    complete: function(){
                        NProgress.done();
                    },
                    success: function(html){
                        $('body').append(html);
                        let modal = $('#modalEditProductCategory');
                        if(modal.length > 0){
                            modal.modal('show');
                        }
                    }
                });
                break;
            }
            case 'delete': {
                if(!confirm('Are you sure to delete?')) return;
                NProgress.start();
                $.ajax({
                    url: '/admin/product-category/delete/' + recordId,
                    type: 'post',
                    dataType: 'json',
                    complete: function(){
                        NProgress.done();
                    },
                    success: function(d){
                        if(d.error){
                            swal('Error Encountered!', d.errorMessage, 'error');
                        }else if(d.success){
                            swal({
                                title: 'Category Deleted Successfully!',
                                text: '',
                                type: 'success'
                            }, function(){
                                location["href"] = location.href;
                            });
                        }
                    }
                });
                break;
            }
        }
    }
</script>
<?php }); ?>

